# COVID-19 Analytics Dashboard
## Part 3 - Data Cleaning & Preprocessing

In [1]:
import pandas as pd
import numpy as np

files=['country_wise_latest.csv','covid_19_clean_complete.csv','day_wise.csv','worldometer_data.csv']
dfs=[pd.read_csv(f) for f in files]
names=['country','clean','day','world']
for name,df in zip(names,dfs):
    print('\nCleaning',name)
    print('Original Shape:',df.shape)
    df.columns=df.columns.str.strip()
    obj=df.select_dtypes(include='object').columns
    for c in obj:
        df[c]=df[c].astype(str).str.strip()
    print('Missing Values Before:')
    print(df.isnull().sum())
    for c in df.columns:
        if df[c].dtype=='object':
            df[c]=df[c].fillna('Unknown')
        else:
            df[c]=df[c].fillna(df[c].median())
    print('Missing Values After:')
    print(df.isnull().sum())
    dup=df.duplicated().sum()
    print('Duplicates:',dup)
    if dup>0:
        df.drop_duplicates(inplace=True)
    print('New Shape:',df.shape)
    print('Data Types:')
    print(df.dtypes)
    print('Summary:')
    display(df.describe(include='all'))
    out=name+'_cleaned.csv'
    df.to_csv(out,index=False)
    print('Saved:',out)

Cleaning country
Original Shape: (187, 15)
Missing Values Before:
Country/Region            0
Confirmed                 0
Deaths                    0
Recovered                 0
Active                    0
New cases                 0
New deaths                0
New recovered             0
Deaths / 100 Cases        0
Recovered / 100 Cases     0
Deaths / 100 Recovered    0
Confirmed last week       0
1 week change             0
1 week % increase         0
WHO Region                0
dtype: int64
Missing Values After:
Country/Region            0
Confirmed                 0
Deaths                    0
Recovered                 0
Active                    0
New cases                 0
New deaths                0
New recovered             0
Deaths / 100 Cases        0
Recovered / 100 Cases     0
Deaths / 100 Recovered    0
Confirmed last week       0
1 week change             0
1 week % increase         0
WHO Region                0
dtype: int64
Duplicates: 0
New Shape: (187, 15)
Data Types:
Country/Region             object
Confirmed                   int64
Deaths                      int64
Recovered                   int64
Active                      int64
New cases                   int64
New deaths                  int64
New recovered               int64
Deaths / 100 Cases        float64
Recovered / 100 Cases     float64
Deaths / 100 Recovered    float64
Confirmed last week         int64
1 week change               int64
1 week % increase         float64
WHO Region                 object
dtype: object
Summary:

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
count,187,1.870000e+02,187.000000,1.870000e+02,1.870000e+02,187.000000,187.000000,187.000000,187.000000,187.000000,187.00,1.870000e+02,187.000000,187.000000,187
unique,187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
top,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Europe
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56
mean,NaN,8.813094e+04,3497.518717,5.063148e+04,3.400194e+04,1222.957219,28.957219,933.812834,3.019519,64.820535,inf,7.868248e+04,9448.459893,13.606203,NaN
std,NaN,3.833187e+05,14100.002482,1.901882e+05,2.133262e+05,5710.374790,120.037173,4197.719635,3.454302,26.287694,NaN,3.382737e+05,47491.127684,24.509838,NaN
min,NaN,1.000000e+01,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,1.000000e+01,-47.000000,-3.840000,NaN
25%,NaN,1.114000e+03,18.500000,6.265000e+02,1.415000e+02,4.000000,0.000000,0.000000,0.945000,48.770000,1.45,1.051500e+03,49.000000,2.775000,NaN
50%,NaN,5.059000e+03,108.000000,2.815000e+03,1.600000e+03,49.000000,1.000000,22.000000,2.150000,71.320000,3.62,5.020000e+03,432.000000,6.890000,NaN
75%,NaN,4.046050e+04,734.000000,2.260600e+04,9.149000e+03,419.500000,6.000000,221.000000,3.875000,86.885000,6.44,3.708050e+04,3172.000000,16.855000,NaN
max,NaN,4.290259e+06,148011.000000,1.846641e+06,2.816444e+06,56336.000000,1076.000000,33728.000000,28.560000,100.000000,inf,3.834677e+06,455582.000000,226.320000,NaN

Saved: country_cleaned.csv

Cleaning clean
Original Shape: (49068, 10)
Missing Values Before:
Province/State    0
Country/Region    0
Lat               0
Long              0
Date              0
Confirmed         0
Deaths            0
Recovered         0
Active            0
WHO Region        0
dtype: int64
Missing Values After:
Province/State    0
Country/Region    0
Lat               0
Long              0
Date              0
Confirmed         0
Deaths            0
Recovered         0
Active            0
WHO Region        0
dtype: int64
Duplicates: 0
New Shape: (49068, 10)
Data Types:
Province/State     object
Country/Region     object
Lat               float64
Long              float64
Date               object
Confirmed           int64
Deaths              int64
Recovered           int64
Active              int64
WHO Region         object
dtype: object
Summary:

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
count,49068,49068,49068.000000,49068.000000,49068,4.906800e+04,49068.000000,4.906800e+04,4.906800e+04,49068
unique,79,187,NaN,NaN,188,NaN,NaN,NaN,NaN,6
top,nan,China,NaN,NaN,2020-01-22,NaN,NaN,NaN,NaN,Europe
freq,34404,6204,NaN,NaN,261,NaN,NaN,NaN,NaN,15040
mean,NaN,NaN,21.433730,23.528236,NaN,1.688490e+04,884.179160,7.915713e+03,8.085012e+03,NaN
std,NaN,NaN,24.950320,70.442740,NaN,1.273002e+05,6313.584411,5.480092e+04,7.625890e+04,NaN
min,NaN,NaN,-51.796300,-135.000000,NaN,0.000000e+00,0.000000,0.000000e+00,-1.400000e+01,NaN
25%,NaN,NaN,7.873054,-15.310100,NaN,4.000000e+00,0.000000,0.000000e+00,0.000000e+00,NaN
50%,NaN,NaN,23.634500,21.745300,NaN,1.680000e+02,2.000000,2.900000e+01,2.600000e+01,NaN
75%,NaN,NaN,41.204380,80.771797,NaN,1.518250e+03,30.000000,6.660000e+02,6.060000e+02,NaN
max,NaN,NaN,71.706900,178.065000,NaN,4.290259e+06,148011.000000,1.846641e+06,2.816444e+06,NaN

Saved: clean_cleaned.csv

Cleaning day
Original Shape: (188, 12)
Missing Values Before:
Date                      0
Confirmed                 0
Deaths                    0
Recovered                 0
Active                    0
New cases                 0
New deaths                0
New recovered             0
Deaths / 100 Cases        0
Recovered / 100 Cases     0
Deaths / 100 Recovered    0
No. of countries          0
dtype: int64
Missing Values After:
Date                      0
Confirmed                 0
Deaths                    0
Recovered                 0
Active                    0
New cases                 0
New deaths                0
New recovered             0
Deaths / 100 Cases        0
Recovered / 100 Cases     0
Deaths / 100 Recovered    0
No. of countries          0
dtype: int64
Duplicates: 0
New Shape: (188, 12)
Data Types:
Date                       object
Confirmed                   int64
Deaths                      int64
Recovered                   int64
Active                      int64
New cases                   int64
New deaths                  int64
New recovered               int64
Deaths / 100 Cases        float64
Recovered / 100 Cases     float64
Deaths / 100 Recovered    float64
No. of countries            int64
dtype: object
Summary:

,Date,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,No. of countries
count,188,1.880000e+02,188.000000,1.880000e+02,1.880000e+02,188.000000,188.000000,188.000000,188.000000,188.000000,188.000000,188.000000
unique,188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2020-01-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,4.406960e+06,230770.760638,2.066001e+06,2.110188e+06,87771.021277,3478.824468,50362.015957,4.860638,34.343936,22.104521,144.351064
std,NaN,4.757988e+06,217929.094183,2.627976e+06,1.969670e+06,75295.293255,2537.735652,56090.892479,1.579541,16.206159,22.568307,65.175979
min,NaN,5.550000e+02,17.000000,2.800000e+01,5.100000e+02,0.000000,0.000000,0.000000,2.040000,1.710000,6.260000,6.000000
25%,NaN,1.121910e+05,3935.000000,6.044125e+04,5.864175e+04,5568.500000,250.750000,2488.250000,3.510000,22.785000,9.650000,101.250000
50%,NaN,2.848733e+06,204190.000000,7.847840e+05,1.859759e+06,81114.000000,4116.000000,30991.500000,4.850000,35.680000,15.380000,184.000000
75%,NaN,7.422046e+06,418634.500000,3.416396e+06,3.587015e+06,131502.500000,5346.000000,79706.250000,6.297500,48.945000,25.342500,187.000000
max,NaN,1.648048e+07,654036.000000,9.468087e+06,6.358362e+06,282756.000000,9966.000000,284394.000000,7.180000,57.450000,134.430000,187.000000

Saved: day_cleaned.csv

Cleaning world
Original Shape: (5, 6)
Missing Values Before:
Country/Region    0
Confirmed         0
Deaths            0
Recovered         0
Active            0
WHO Region        0
dtype: int64
Missing Values After:
Country/Region    0
Confirmed         0
Deaths            0
Recovered         0
Active            0
WHO Region        0
dtype: int64
Duplicates: 0
New Shape: (5, 6)
Data Types:
Country/Region    object
Confirmed          int64
Deaths             int64
Recovered          int64
Active             int64
WHO Region        object
dtype: object
Summary:

,Country/Region,Confirmed,Deaths,Recovered,Active,WHO Region
count,5,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5
unique,5,NaN,NaN,NaN,NaN,4
top,World,NaN,NaN,NaN,NaN,Americas
freq,1,NaN,NaN,NaN,NaN,2
mean,NaN,1.816000e+08,1.930000e+06,1.759200e+08,3.734000e+06,NaN
std,NaN,2.913929e+08,2.791541e+06,2.806136e+08,8.031362e+06,NaN
min,NaN,2.300000e+07,4.000000e+05,2.250000e+07,7.000000e+04,NaN
25%,NaN,3.700000e+07,5.300000e+05,3.620000e+07,1.000000e+05,NaN
50%,NaN,4.500000e+07,7.000000e+05,4.440000e+07,1.000000e+05,NaN
75%,NaN,1.030000e+08,1.120000e+06,1.015000e+08,3.000000e+05,NaN
max,NaN,7.000000e+08,6.900000e+06,6.750000e+08,1.810000e+07,NaN

Saved: world_cleaned.csv

### Part 3 Completed
All datasets cleaned and exported for further analysis.